apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gin
spec:
  type: {{ .Values.gin.service.type }}
  selector:
    app: datetime-server-gin
  ports:
  - port: {{ .Values.gin.service.port }}
    targetPort: {{ .Values.gin.service.targetPort }}